### ISSUE TITLE
No result is returning

### ISSUE THREAD

**Issue by hackison** [Anon-Exploiter/SiteBroker#9]
No results is coming?? i tried cloudflare bypass it is not working and tried crawler it is not returning the result. Please see the screenshot
![screenshot 35](https://user-images.githubusercontent.com/39798618/50749966-4b419a00-1268-11e9-9340-155677acf6e6.png)

**Comment by Anon-Exploiter** [comment]
Hi there,

It seems like an issue on your end, since its working absolutely fine for me. Have you tried using a virtual environment for python libraries? 

Here's the link to [Installing VirtualEnv](https://github.com/Anon-Exploiter/SiteBroker/issues/4#issuecomment-421292969)

![image](https://user-images.githubusercontent.com/18597330/50752589-98296e80-1270-11e9-87a8-3c8e6825fdcb.png)

PS ~ For cloudflare, I've integrated a third-party website **crimeflare.org**, it seems the site's down. As soon as its up and running that module will be usable.

**Comment by hackison** [comment]
Im using kali linux subsystem in windows 10

**Comment by hackison** [comment]
Manual crawling is working whereas google and bin is not producing any results

**Comment by Anon-Exploiter** [comment]
Hi, @hackison sometimes due to crawling and stuff, google shows captcha and the script won't be able to run that module in that case :) 

If there was some issue, I've fixed all those, currently its working fine for me. You may wanna pull the latest [release](https://github.com/Anon-Exploiter/SiteBroker/commit/a4e88c0ca078500c0d4f7d5a36400fb2e806c065) and try again.
